# --- General options --- #
url: "http://hpsilva.github.io"
baseurl: ""
title: 'hpsilva'

# --- Navigation bar options --- #
#avatar: "https://avatars2.githubusercontent.com/u/11724991?v=3&s=460"

navbar-links:
  
  Blog: "http://hpsilva.io"
  Resources:
    - Market Snapshot: "snapshot"
    - Correlation Heatmap: "correlatio"
    - Market Sentiment: "http://hpsilva.io"
  Systems: "systems"
  About: "about"
  LOGIN: "http://hpsilva.io"


# --- Footer options --- #
author:
  name: hpsilva
  email: "contact@hpsilva.io"
  facebook: yourname  # eg. daattali
  github: hpsilva    # eg. daattali
  twitter: hpsilva_   # eg. daattali
  linkedin: yourlink  # eg. "pub/dean-attali/8/946/143"
  stackoverflow: 5216240/hpsilva  # eg. "3943160/daattali"
 
# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: true

url-pretty: "hpsilva.io"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #
disqus: "hpsilva"
google_analytics: "UA-67737750-1"


# Output options (more information on Jekyll's site)
timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text" 
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

